name: Build SteamModuleFix

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build Pandora Legacy
      run: msbuild SteamModuleFix.slnx /p:Configuration="Pandora Legacy" /p:Platform=x64

    - name: Build Pandora Desync
      run: msbuild SteamModuleFix.slnx /p:Configuration="Pandora Desync" /p:Platform=x64

    - name: Upload Output DLLs
      uses: actions/upload-artifact@v4
      with:
        name: SteamModuleFix-Pandora
        path: |
          **/*.dll
