name: Build Pandora Legacy

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build Pandora Legacy (x64)
      run: |
        msbuild SteamModuleFix/SteamModuleFix.vcxproj /p:Configuration="Pandora Legacy" /p:Platform="x64"

    - name: Upload Output Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Pandora-Legacy-x64
        path: |
          Dll/*.dll
